name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Stop existing container
        run: docker stop portfolio-nuxt || true

      - name: Remove existing container
        run: docker rm portfolio-nuxt || true

      - name: Run Docker container
        run: docker run -d --name portfolio-nuxt -p 80:80 portfolio:latest
