name: Scan

on:
  push:
    branches:
      - main
      - Features/*


jobs:
  scan:
    name: Scan Source Code
    runs-on: [ self-hosted ]

    steps:
      - name: Check out the repo
      - uses: actions/checkout@v4

      - name: Exectute sonarqube scan
      - run: sonar-scanner -Dsonar.projectKey=portfolio -Dsonar.sources=. -Dsonar.host.url=${{ secrets.SONAR_HOST }} -Dsonar.token=${{ secrets.SONAR_TOKEN }}
